### ISSUE TITLE
  OSError: mysql_config not found

### ISSUE THREAD

**Issue by jen-soft** [rutube/django_sphinxsearch#45]
Hello, i am use sphinx in docker

(env: jen-soft) user@DEV:~/projects/jen-soft$ pip install django_sphinxsearch
Collecting django_sphinxsearch
  Using cached https://files.pythonhosted.org/packages/6d/7f/e6ad367fcc8dee88ddaa307ff05880d83ef36d8c113679afa85705c8526c/django_sphinxsearch-3.3.0.tar.gz
    Complete output from command python setup.py egg_info:
    /bin/sh: 1: mysql_config: not found
    /bin/sh: 1: mariadb_config: not found
    /bin/sh: 1: mysql_config: not found
    Traceback (most recent call last):
      File "/home/user/.venv/jen-soft/lib/python3.6/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/home/user/.venv/jen-soft/lib/python3.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/home/user/.venv/jen-soft/lib/python3.6/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/home/user/.venv/jen-soft/lib/python3.6/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-3rhlm2ph/mysqlclient-1.4.4/setup.py", line 16, in <module>
        Reads version from git status or PKG-INFO
      File "/tmp/easy_install-3rhlm2ph/mysqlclient-1.4.4/setup_posix.py", line 61, in get_config
      File "/tmp/easy_install-3rhlm2ph/mysqlclient-1.4.4/setup_posix.py", line 29, in mysql_config
    OSError: mysql_config not found
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-zgnh0mfk/django-sphinxsearch/setup.py", line 78, in <module>
        'pytz'
      File "/home/user/.venv/jen-soft/lib/python3.6/site-packages/setuptools/__init__.py", line 142, in setup
        _install_setup_requires(attrs)
      File "/home/user/.venv/jen-soft/lib/python3.6/site-packages/setuptools/__init__.py", line 137, in _install_setup_requires
        dist.fetch_build_eggs(dist.setup_requires)
      File "/home/user/.venv/jen-soft/lib/python3.6/site-packages/setuptools/dist.py", line 586, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/user/.venv/jen-soft/lib/python3.6/site-packages/pkg_resources/__init__.py", line 780, in resolve
        replace_conflicting=replace_conflicting
      File "/home/user/.venv/jen-soft/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1063, in best_match
        return self.obtain(req, installer)
      File "/home/user/.venv/jen-soft/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1075, in obtain
        return installer(requirement)
      File "/home/user/.venv/jen-soft/lib/python3.6/site-packages/setuptools/dist.py", line 653, in fetch_build_egg
        return cmd.easy_install(req)
      File "/home/user/.venv/jen-soft/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 679, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/home/user/.venv/jen-soft/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 705, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/home/user/.venv/jen-soft/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 890, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/home/user/.venv/jen-soft/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1158, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/home/user/.venv/jen-soft/lib/python3.6/site-packages/setuptools/command/easy_install.py", line 1144, in run_setup
        run_setup(setup_script, args)
      File "/home/user/.venv/jen-soft/lib/python3.6/site-packages/setuptools/sandbox.py", line 253, in run_setup
        raise
      File "/usr/local/lib/python3.6/contextlib.py", line 99, in __exit__
        self.gen.throw(type, value, traceback)
      File "/home/user/.venv/jen-soft/lib/python3.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/usr/local/lib/python3.6/contextlib.py", line 99, in __exit__
        self.gen.throw(type, value, traceback)
      File "/home/user/.venv/jen-soft/lib/python3.6/site-packages/setuptools/sandbox.py", line 166, in save_modules
        saved_exc.resume()
      File "/home/user/.venv/jen-soft/lib/python3.6/site-packages/setuptools/sandbox.py", line 141, in resume
        six.reraise(type, exc, self._tb)
      File "/home/user/.venv/jen-soft/lib/python3.6/site-packages/setuptools/_vendor/six.py", line 685, in reraise
        raise value.with_traceback(tb)
      File "/home/user/.venv/jen-soft/lib/python3.6/site-packages/setuptools/sandbox.py", line 154, in save_modules
        yield saved
      File "/home/user/.venv/jen-soft/lib/python3.6/site-packages/setuptools/sandbox.py", line 195, in setup_context
        yield
      File "/home/user/.venv/jen-soft/lib/python3.6/site-packages/setuptools/sandbox.py", line 250, in run_setup
        _execfile(setup_script, ns)
      File "/home/user/.venv/jen-soft/lib/python3.6/site-packages/setuptools/sandbox.py", line 45, in _execfile
        exec(code, globals, locals)
      File "/tmp/easy_install-3rhlm2ph/mysqlclient-1.4.4/setup.py", line 16, in <module>
        Reads version from git status or PKG-INFO
      File "/tmp/easy_install-3rhlm2ph/mysqlclient-1.4.4/setup_posix.py", line 61, in get_config
      File "/tmp/easy_install-3rhlm2ph/mysqlclient-1.4.4/setup_posix.py", line 29, in mysql_config
    OSError: mysql_config not found
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-zgnh0mfk/django-sphinxsearch/
You are using pip version 18.1, however version 19.2.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by tumb1er** [comment]
You need `libmysqlclient-dev` to be installed in docker container.

**Comment by jen-soft** [comment]
tumb1er 
libmysqlclient-dev - thanks, this is helped

**Comment by jen-soft** [comment]
* source repo of pypi package is here
https://github.com/tumb1er/django_sphinxsearch
